dist: xenial
language: rust
rust:
- stable
- beta
- nightly
cache: cargo
before_install:
- sudo apt-get update
- sudo apt-get install -y python3 python3-dev
- sudo ln -sf /usr/bin/python3 /usr/bin/python
script:
- cargo build --all-features
- cargo test --all-features
