dist: xenial
language: rust
matrix:
  include:
  - rust: stable
    env: FEATURES=""
  - rust: beta
    env: FEATURES=""
  - rust: nightly
    env: FEATURES="--all-features"
cache: cargo
before_install:
- sudo apt-get update
- sudo apt-get install -y python3 python3-dev
- sudo ln -sf /usr/bin/python3 /usr/bin/python
script:
- cargo build ${FEATURES}
- cargo test ${FEATURES}
