[package]
name = "ymlctx"
version = "0.0.2"
authors = ["Alex Yang <aleozlx@gmail.com>"]
description = "YAML configuration overlaying system that natively integrates into operationalized tasks"
license = "MIT"
edition = "2018"

[dependencies]
yaml-rust = "0.4"
rpds = "0.5.0"
linked-hash-map = ">=0.0.9, <0.6"
pyo3 = "0.5"
