[package]
name = "ymlctx"
version = "0.1.0"
authors = ["Alex Yang <aleozlx@gmail.com>"]
edition = "2018"
description = "YAML configuration overlaying system that natively integrates into jobs"

[dependencies]
yaml-rust = "0.4"
rpds = "*"
linked-hash-map = ">=0.0.9, <0.6"
pyo3 = "0.5"
